title: Marc Morente
description: Construyo artículos sobre conceptos nuevos que están relacionados con IA para aprender y compartir conocimientos.
url: "https://marcmorente.github.io"

theme: minima


show_excerpts: true

permalink: /:title/

plugins:
  - jekyll-feed
