title: Marc Morente
description: Writing about software, people, and ideas.
url: "https://marcmorente.github.io"

theme: minima

header_pages: []

show_excerpts: true

permalink: /:title/

plugins:
  - jekyll-feed
